# [colors.bright]
# black = "#625e4c"
# blue = "#9d65ff"
# cyan = "#58d1eb"
# green = "#98e024"
# magenta = "#f4005f"
# red = "#f4005f"
# white = "#f6f6ef"
# yellow = "#e0d561"

# [colors.normal]
# black = "#1a1a1a"
# blue = "#9d65ff"
# cyan = "#58d1eb"
# green = "#98e024"
# magenta = "#f4005f"
# red = "#f4005f"
# white = "#c4c5b5"
# yellow = "#fa8419"

# [colors.primary]
# background = "#1a1a1a"
# foreground = "#c4c5b5"

# Default Colors
[colors.primary]
background = '#121212'
foreground = '#f5f5f5'

# Selection Colors
[colors.cursor]
cursor = '#f5f5f5'
text = '#121212'

# Normal Colors
[colors.normal]
black = '#121212'
red = '#B14242'
green = '#D87C4A'
yellow = '#E49A44'
blue = '#4A8B8B'
magenta = '#a7a7a7'
cyan = '#b4b4b4'
white = '#d5d5d5'

# Bright Colors
[colors.bright]
black = '#949494'
red = '#B14242'
green = '#D87C4A'
yellow = '#E49A44'
blue = '#4A8B8B'
magenta = '#a7a7a7'
cyan = '#b4b4b4'
white = '#d5d5d5'

[font]
size = 16.0

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
startup_mode = "Maximized"
